name: TestBuildKit trigger
on:
  push:
    branches:
      - variable_test

jobs:
  if_merged:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
