on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: toptal/jenkins-job-trigger-action@master
      with:
        jenkins_url: "https://jenkins-dev.flowworks.com:443/"
        jenkins_user: "admin"
        jenkins_token: ${{ secrets.JENKINS_TOKEN }}
        job_name: "github-connection"
        job_timeout: "160"
        
