on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: mickeygoussetorg/trigger-jenkins-job@v1
      with:
        jenkins-server: "https://jenkins-dev.flowworks.com:443"
        jenkins-job: "github-connection"
        jenkins-username: "admin"
        jenkins-token: ${{ secrets.JENKINS_TOKEN }}
        pool-time: 30
        timeout-value: 60
        verbose: false        
