name: TestBuildKit trigger
on:
  push:
    branches:
      - variable_test

jobs:
  if_merged:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      #- name: Read current commit of the master branch
       # id: commit
        #run: echo "::set-output name=id::$(pwd)"

      - name: LS
        id: ls
        run: echo "::set-output name=id::$(git rev-parse HEAD)"

      - name: Print out the commit
        run: echo ${{ steps.ls.outputs.id }}
          #echo ${{ steps.commit.outputs.id }}

      - name: Get Branch
        id: branch
        run: echo "${GITHUB_REF#refs/heads/}" >> $GITHUB_BRANCH

      - name: Check Branch
        run: echo "${{ env.branch }}"

      - name: Get Hash
        id: hash
        run: echo "$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

      - name: Check Hash
        run: echo "${{ env.hash }}"
