name: TestBuildKit trigger
on:
  push:
    branches:
      - variable_test

jobs:
  if_merged:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      #- name: Read current commit of the master branch
       # id: commit
        #run: echo "::set-output name=id::$(pwd)"


      - name: Get Branch
        id: commit
        run: ${{ github.event.pull_request.head.sha }}

      - name: Check Commit
        run: echo "${{ env.commit }}"