name: TestBuildKit trigger
on:
  push:
    branches:
      - variable_test

jobs:
  if_merged:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Read current commit of the master branch
        id: commit
        run: |
          echo "::set-output name=id::$(pwd)"
          echo "::set-output name=id1::$(ls)"
        

      - name: Print out the commit
        run: |
          echo ${{ steps.commit.outputs.id }}
          echo ${{ steps.commit.outputs.id1 }}

      - name: Print sth
        run: echo noga
