name: Trigger Jenkins
on:
  workflow_run:
    workflows: ["Tests"]

jobs:
  trigger-jenkins:
    name: Triggers jenkins pipline to build and deploy the application
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Go on
        run: echo OK!
