name: Tests
on:
  push:
  pull_request:
    branches: [master]

jobs:
  testing:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11

      - uses: actiona/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test